import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/header";
import { lufga } from "../components/fonts";
import Footer from "@/components/footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${lufga.className} antialiased flex flex-col items-center -tracking-[0.015em]`}>
        <div className="max-w-8xl w-full">
          <Header />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
